// Copyright 2026 Simon Zünd
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// genbridge generates tsccbridge/bridge.go inside the typescript-go submodule.
// That package re-exports the symbols from internal/execute that tscc needs,
// working around Go's rule that internal/ packages cannot be imported from
// outside the module that owns them.
//
// Run via: go generate ./...
package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const bridgeContent = `// Code generated by "go generate"; DO NOT EDIT.

package tsccbridge

import (
	"github.com/microsoft/typescript-go/internal/bundled"
	"github.com/microsoft/typescript-go/internal/compiler"
	"github.com/microsoft/typescript-go/internal/core"
	"github.com/microsoft/typescript-go/internal/execute"
	"github.com/microsoft/typescript-go/internal/execute/tsc"
	"github.com/microsoft/typescript-go/internal/module"
	"github.com/microsoft/typescript-go/internal/packagejson"
	"github.com/microsoft/typescript-go/internal/tsoptions"
	"github.com/microsoft/typescript-go/internal/tspath"
	"github.com/microsoft/typescript-go/internal/vfs"
	"github.com/microsoft/typescript-go/internal/vfs/osvfs"
)

// Type aliases expose internal types to external modules without requiring
// direct imports of internal/ packages.
type System             = tsc.System
type CommandLineResult  = tsc.CommandLineResult
type ExitStatus         = tsc.ExitStatus
type CommandLineTesting = tsc.CommandLineTesting
type Watcher            = tsc.Watcher
type FS                 = vfs.FS
type Entries            = vfs.Entries

// Programmatic compilation API types.
type CompilerOptions     = core.CompilerOptions
type ScriptTarget        = core.ScriptTarget
type Tristate            = core.Tristate
type ParsedCommandLine   = tsoptions.ParsedCommandLine
type ComparePathsOptions = tspath.ComparePathsOptions
type CompilerHost        = compiler.CompilerHost
type ProgramOptions      = compiler.ProgramOptions
type Program             = compiler.Program
type EmitOptions         = compiler.EmitOptions
type EmitResult          = compiler.EmitResult
type WriteFile           = compiler.WriteFile
type WriteFileData       = compiler.WriteFileData
type ModuleResolver      = module.ModuleResolver
type ResolutionMode      = core.ResolutionMode
type ResolvedModule      = module.ResolvedModule
type ResolvedProjectReference = module.ResolvedProjectReference
type ResolvedTypeReferenceDirective = module.ResolvedTypeReferenceDirective
type DiagAndArgs         = module.DiagAndArgs
type InfoCacheEntry      = packagejson.InfoCacheEntry

// NewParsedCommandLine bundles CompilerOptions with the root file list and
// path-comparison settings, ready to feed into compiler.NewProgram.
var NewParsedCommandLine = tsoptions.NewParsedCommandLine

// NewProgram creates a new TypeScript compilation program.
var NewProgram = compiler.NewProgram

// CompilerHost constructors. NewCachedFSCompilerHost wraps its FS in a cache;
// NewCompilerHost uses the FS as-is.
var (
	NewCompilerHost        = compiler.NewCompilerHost
	NewCachedFSCompilerHost = compiler.NewCachedFSCompilerHost
)

// CreateCompilerHost is a simplified constructor for tscc that passes nil for
// the caches and trace functions that tscc doesn't use yet.
func CreateCompilerHost(cwd string, fs FS, defaultLibPath string) CompilerHost {
	return compiler.NewCompilerHost(cwd, fs, defaultLibPath, nil, nil)
}

// OSFS returns the live OS-backed vfs.FS.
var OSFS = osvfs.FS

// DefaultLibPath returns the path to the bundled lib.d.ts files. When tsgo is
// built with embedding enabled (the default), this is a virtual path served by
// bundled.WrapFS — callers that read from it must route their FS through
// bundled.WrapFS.
var DefaultLibPath = bundled.LibPath

// CommandLine is the top-level entry point for TypeScript compilation,
// mirroring what cmd/tsgo/main.go does. Pass nil for testing in production.
var CommandLine = execute.CommandLine

// ExitStatus constants, re-exported so callers do not need to reference
// the internal/execute/tsc package by name.
const (
	ExitStatusSuccess                              ExitStatus = 0
	ExitStatusDiagnosticsPresent_OutputsGenerated  ExitStatus = 1
	ExitStatusDiagnosticsPresent_OutputsSkipped    ExitStatus = 2
	ExitStatusInvalidProject_OutputsSkipped        ExitStatus = 3
	ExitStatusProjectReferenceCycle_OutputsSkipped ExitStatus = 4
	ExitStatusNotImplemented                       ExitStatus = 5
)

// ScriptTarget constants cover the --target values tscc accepts.
const (
	ScriptTargetES2015 ScriptTarget = core.ScriptTargetES2015
	ScriptTargetES2016 ScriptTarget = core.ScriptTargetES2016
	ScriptTargetES2017 ScriptTarget = core.ScriptTargetES2017
	ScriptTargetES2018 ScriptTarget = core.ScriptTargetES2018
	ScriptTargetES2019 ScriptTarget = core.ScriptTargetES2019
	ScriptTargetES2020 ScriptTarget = core.ScriptTargetES2020
	ScriptTargetES2021 ScriptTarget = core.ScriptTargetES2021
	ScriptTargetES2022 ScriptTarget = core.ScriptTargetES2022
	ScriptTargetES2023 ScriptTarget = core.ScriptTargetES2023
	ScriptTargetES2024 ScriptTarget = core.ScriptTargetES2024
	ScriptTargetES2025 ScriptTarget = core.ScriptTargetES2025
	ScriptTargetESNext ScriptTarget = core.ScriptTargetESNext
)

// ModuleKind API types.
type ModuleKind = core.ModuleKind

const (
	ModuleKindESNext ModuleKind = core.ModuleKindESNext
)

// Tristate constants.
const (
	TSUnknown Tristate = core.TSUnknown
	TSFalse   Tristate = core.TSFalse
	TSTrue    Tristate = core.TSTrue
)
`

func main() {
	moduleRoot, err := findModuleRoot()
	if err != nil {
		fmt.Fprintf(os.Stderr, "genbridge: %v\n", err)
		os.Exit(1)
	}

	outDir := filepath.Join(moduleRoot, "third_party", "typescript-go", "tsccbridge")
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "genbridge: failed to create output directory: %v\n", err)
		os.Exit(1)
	}

	outFile := filepath.Join(outDir, "bridge.go")
	if err := os.WriteFile(outFile, []byte(bridgeContent), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "genbridge: failed to write bridge file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("genbridge: wrote %s\n", outFile)

	patchFile := filepath.Join(moduleRoot, "patches", "inject-resolver.patch")
	tsgoDir := filepath.Join(moduleRoot, "third_party", "typescript-go")
	if err := applyPatch(tsgoDir, patchFile); err != nil {
		fmt.Fprintf(os.Stderr, "genbridge: %v\n", err)
		os.Exit(1)
	}
}

func applyPatch(dir, patchFile string) error {
	// Check if already applied by trying a reverse patch dry-run
	cmdCheck := exec.Command("git", "apply", "--reverse", "--check", patchFile)
	cmdCheck.Dir = dir
	if err := cmdCheck.Run(); err == nil {
		// Reverse patch applies cleanly, meaning the patch is already applied
		return nil
	}

	// Not applied, let's apply it
	cmdApply := exec.Command("git", "apply", patchFile)
	cmdApply.Dir = dir
	out, err := cmdApply.CombinedOutput()
	if err != nil {
		return fmt.Errorf("failed to apply patch %s: %v\n%s", patchFile, err, out)
	}
	fmt.Printf("genbridge: applied patch %s\n", filepath.Base(patchFile))
	return nil
}

// findModuleRoot returns the directory containing the go.mod for
// github.com/szuend/tscc by asking the Go toolchain.
func findModuleRoot() (string, error) {
	out, err := exec.Command("go", "env", "GOMOD").Output()
	if err != nil {
		return "", fmt.Errorf("could not determine module root: %w", err)
	}
	gomod := strings.TrimSpace(string(out))
	if gomod == "" || gomod == os.DevNull {
		return "", fmt.Errorf("not inside a Go module (go env GOMOD returned %q)", gomod)
	}
	return filepath.Dir(gomod), nil
}
