// Copyright 2026 Simon Zünd
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// genbridge generates tsccbridge/bridge.go inside the typescript-go submodule.
// That package re-exports the symbols from internal/execute that tscc needs,
// working around Go's rule that internal/ packages cannot be imported from
// outside the module that owns them.
//
// Run via: go generate ./...
package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const bridgeContent = `// Code generated by "go generate"; DO NOT EDIT.

package tsccbridge

import (
	"github.com/microsoft/typescript-go/internal/core"
	"github.com/microsoft/typescript-go/internal/execute"
	"github.com/microsoft/typescript-go/internal/execute/tsc"
	"github.com/microsoft/typescript-go/internal/vfs"
)

// Type aliases expose internal types to external modules without requiring
// direct imports of internal/ packages.
type System             = tsc.System
type CommandLineResult  = tsc.CommandLineResult
type ExitStatus         = tsc.ExitStatus
type CommandLineTesting = tsc.CommandLineTesting
type Watcher            = tsc.Watcher
type FS                 = vfs.FS

// Programmatic compilation API types.
type CompilerOptions = core.CompilerOptions
type ScriptTarget    = core.ScriptTarget
type Tristate        = core.Tristate

// CommandLine is the top-level entry point for TypeScript compilation,
// mirroring what cmd/tsgo/main.go does. Pass nil for testing in production.
var CommandLine = execute.CommandLine

// ExitStatus constants, re-exported so callers do not need to reference
// the internal/execute/tsc package by name.
const (
	ExitStatusSuccess                              ExitStatus = 0
	ExitStatusDiagnosticsPresent_OutputsGenerated  ExitStatus = 1
	ExitStatusDiagnosticsPresent_OutputsSkipped    ExitStatus = 2
	ExitStatusInvalidProject_OutputsSkipped        ExitStatus = 3
	ExitStatusProjectReferenceCycle_OutputsSkipped ExitStatus = 4
	ExitStatusNotImplemented                       ExitStatus = 5
)

// ScriptTarget constants cover the --target values tscc accepts.
const (
	ScriptTargetES2015 ScriptTarget = core.ScriptTargetES2015
	ScriptTargetES2016 ScriptTarget = core.ScriptTargetES2016
	ScriptTargetES2017 ScriptTarget = core.ScriptTargetES2017
	ScriptTargetES2018 ScriptTarget = core.ScriptTargetES2018
	ScriptTargetES2019 ScriptTarget = core.ScriptTargetES2019
	ScriptTargetES2020 ScriptTarget = core.ScriptTargetES2020
	ScriptTargetES2021 ScriptTarget = core.ScriptTargetES2021
	ScriptTargetES2022 ScriptTarget = core.ScriptTargetES2022
	ScriptTargetES2023 ScriptTarget = core.ScriptTargetES2023
	ScriptTargetES2024 ScriptTarget = core.ScriptTargetES2024
	ScriptTargetES2025 ScriptTarget = core.ScriptTargetES2025
	ScriptTargetESNext ScriptTarget = core.ScriptTargetESNext
)

// Tristate constants.
const (
	TSUnknown Tristate = core.TSUnknown
	TSFalse   Tristate = core.TSFalse
	TSTrue    Tristate = core.TSTrue
)
`

func main() {
	moduleRoot, err := findModuleRoot()
	if err != nil {
		fmt.Fprintf(os.Stderr, "genbridge: %v\n", err)
		os.Exit(1)
	}

	outDir := filepath.Join(moduleRoot, "third_party", "typescript-go", "tsccbridge")
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "genbridge: failed to create output directory: %v\n", err)
		os.Exit(1)
	}

	outFile := filepath.Join(outDir, "bridge.go")
	if err := os.WriteFile(outFile, []byte(bridgeContent), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "genbridge: failed to write bridge file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("genbridge: wrote %s\n", outFile)
}

// findModuleRoot returns the directory containing the go.mod for
// github.com/szuend/tscc by asking the Go toolchain.
func findModuleRoot() (string, error) {
	out, err := exec.Command("go", "env", "GOMOD").Output()
	if err != nil {
		return "", fmt.Errorf("could not determine module root: %w", err)
	}
	gomod := strings.TrimSpace(string(out))
	if gomod == "" || gomod == os.DevNull {
		return "", fmt.Errorf("not inside a Go module (go env GOMOD returned %q)", gomod)
	}
	return filepath.Dir(gomod), nil
}
