// Copyright 2026 Simon Zünd
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// genbridge generates tsccbridge/bridge.go inside the typescript-go submodule.
// That package re-exports the symbols from internal/execute that tscc needs,
// working around Go's rule that internal/ packages cannot be imported from
// outside the module that owns them.
//
// Run via: go generate ./...
package main

import (
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const bridgeContent = `// Code generated by "go generate"; DO NOT EDIT.

package tsccbridge

import (
	"io"

	"github.com/microsoft/typescript-go/internal/ast"
	"github.com/microsoft/typescript-go/internal/bundled"
	"github.com/microsoft/typescript-go/internal/collections"
	"github.com/microsoft/typescript-go/internal/compiler"
	"github.com/microsoft/typescript-go/internal/core"
	"github.com/microsoft/typescript-go/internal/diagnostics"
	"github.com/microsoft/typescript-go/internal/diagnosticwriter"
	"github.com/microsoft/typescript-go/internal/execute"
	"github.com/microsoft/typescript-go/internal/execute/tsc"
	"github.com/microsoft/typescript-go/internal/module"
	"github.com/microsoft/typescript-go/internal/packagejson"
	"github.com/microsoft/typescript-go/internal/parser"
	"github.com/microsoft/typescript-go/internal/testrunner"
	"github.com/microsoft/typescript-go/internal/tsoptions"
	"github.com/microsoft/typescript-go/internal/tspath"
	"github.com/microsoft/typescript-go/internal/vfs"
	"github.com/microsoft/typescript-go/internal/vfs/osvfs"
)

// Type aliases expose internal types to external modules without requiring
// direct imports of internal/ packages.
type System             = tsc.System
type CommandLineResult  = tsc.CommandLineResult
type ExitStatus         = tsc.ExitStatus
type CommandLineTesting = tsc.CommandLineTesting
type Watcher            = tsc.Watcher
type FS                 = vfs.FS
type Entries            = vfs.Entries

// Programmatic compilation API types.
type CompilerOptions     = core.CompilerOptions
type ScriptTarget        = core.ScriptTarget
type Tristate            = core.Tristate
type ParsedCommandLine   = tsoptions.ParsedCommandLine
type ComparePathsOptions = tspath.ComparePathsOptions
type CompilerHost        = compiler.CompilerHost
type ProgramOptions      = compiler.ProgramOptions
type Program             = compiler.Program
type EmitOptions         = compiler.EmitOptions
type EmitResult          = compiler.EmitResult
type WriteFile           = compiler.WriteFile
type WriteFileData       = compiler.WriteFileData
type ModuleResolver      = module.ModuleResolver
type ResolutionMode      = core.ResolutionMode
type ResolvedModule      = module.ResolvedModule
type ResolvedProjectReference = module.ResolvedProjectReference
type ResolvedTypeReferenceDirective = module.ResolvedTypeReferenceDirective
type DiagAndArgs         = module.DiagAndArgs
type InfoCacheEntry      = packagejson.InfoCacheEntry
type ProgramLike         = compiler.ProgramLike
type Diagnostic          = ast.Diagnostic
type DiagnosticCategory  = diagnostics.Category

const (
	DiagnosticCategoryWarning    DiagnosticCategory = diagnostics.CategoryWarning
	DiagnosticCategoryError      DiagnosticCategory = diagnostics.CategoryError
	DiagnosticCategorySuggestion DiagnosticCategory = diagnostics.CategorySuggestion
	DiagnosticCategoryMessage    DiagnosticCategory = diagnostics.CategoryMessage
)

// GetDiagnosticsOfAnyProgram mirrors tsc's collection order: config-file
// diagnostics, then syntactic, then program, then (if still clean) global,
// semantic, and finally declaration — short-circuiting as earlier categories
// fire, same as the upstream binary.
var GetDiagnosticsOfAnyProgram = compiler.GetDiagnosticsOfAnyProgram

// SortAndDeduplicateDiagnostics canonicalizes a diagnostic slice so output is
// stable across runs.
var SortAndDeduplicateDiagnostics = compiler.SortAndDeduplicateDiagnostics

// FormatDiagnostic writes d to out in tsc's plain (non-color) format. cwd and
// useCaseSensitive are used solely to render file paths relative to the cwd.
func FormatDiagnostic(out io.Writer, d *ast.Diagnostic, cwd string, useCaseSensitive bool) {
	diagnosticwriter.WriteFormatDiagnostic(out, diagnosticwriter.WrapASTDiagnostic(d), &diagnosticwriter.FormattingOptions{
		NewLine: "\n",
		ComparePathsOptions: tspath.ComparePathsOptions{
			CurrentDirectory:          cwd,
			UseCaseSensitiveFileNames: useCaseSensitive,
		},
	})
}

// NewParsedCommandLine bundles CompilerOptions with the root file list and
// path-comparison settings, ready to feed into compiler.NewProgram.
var NewParsedCommandLine = tsoptions.NewParsedCommandLine

// GetLibFileName resolves a lib name to its corresponding file name.
var GetLibFileName = tsoptions.GetLibFileName

// NewProgram creates a new TypeScript compilation program.
var NewProgram = compiler.NewProgram

// NewDualFSHost returns a CompilerHost whose FS() reports jailedFS (used by
// every discovery probe) and whose GetSourceFile reads from rawFS directly
// (so explicit paths like an import of "./package.json" work even though the
// jailed FS blocks discovery of configuration files). See design §7.
func NewDualFSHost(cwd string, jailedFS FS, rawFS FS, defaultLibPath string) CompilerHost {
	return &dualFSHost{
		cwd:                cwd,
		jailedFS:           jailedFS,
		rawFS:              rawFS,
		defaultLibraryPath: defaultLibPath,
	}
}

type dualFSHost struct {
	cwd                string
	jailedFS           vfs.FS
	rawFS              vfs.FS
	defaultLibraryPath string
}

func (h *dualFSHost) FS() vfs.FS                 { return h.jailedFS }
func (h *dualFSHost) DefaultLibraryPath() string { return h.defaultLibraryPath }
func (h *dualFSHost) GetCurrentDirectory() string { return h.cwd }
func (h *dualFSHost) Trace(msg *diagnostics.Message, args ...any) {}
func (h *dualFSHost) GetSourceFile(opts ast.SourceFileParseOptions) *ast.SourceFile {
	text, ok := h.rawFS.ReadFile(opts.FileName)
	if !ok {
		return nil
	}
	return parser.ParseSourceFile(opts, text, core.GetScriptKindFromFileName(opts.FileName))
}
func (h *dualFSHost) GetResolvedProjectReference(fileName string, path tspath.Path) *tsoptions.ParsedCommandLine {
	return nil
}

// OSFS returns the live OS-backed vfs.FS.
var OSFS = osvfs.FS

// BundledWrapFS layers typescript-go's bundled-lib redirection over an FS.
// Production callers stack it outside hermeticfs so bundled://libs reads are
// intercepted before hitting the jail.
var BundledWrapFS = bundled.WrapFS

// DefaultLibPath returns the path to the bundled lib.d.ts files. When tsgo is
// built with embedding enabled (the default), this is a virtual path served by
// bundled.WrapFS — callers that read from it must route their FS through
// bundled.WrapFS.
var DefaultLibPath = bundled.LibPath

// IsBundled reports whether a path refers to a typescript-go-embedded lib
// file (served via bundled.WrapFS under the "bundled:///" scheme). Callers
// that enumerate program.SourceFiles() use it to drop the embedded libs,
// which have no on-disk location a build system can stat.
var IsBundled = bundled.IsBundled

// CommandLine is the top-level entry point for TypeScript compilation,
// mirroring what cmd/tsgo/main.go does. Pass nil for testing in production.
var CommandLine = execute.CommandLine

// ExitStatus constants, re-exported so callers do not need to reference
// the internal/execute/tsc package by name.
const (
	ExitStatusSuccess                              ExitStatus = 0
	ExitStatusDiagnosticsPresent_OutputsGenerated  ExitStatus = 1
	ExitStatusDiagnosticsPresent_OutputsSkipped    ExitStatus = 2
	ExitStatusInvalidProject_OutputsSkipped        ExitStatus = 3
	ExitStatusProjectReferenceCycle_OutputsSkipped ExitStatus = 4
	ExitStatusNotImplemented                       ExitStatus = 5
)

// ScriptTarget constants cover the --target values tscc accepts.
const (
	ScriptTargetES2015 ScriptTarget = core.ScriptTargetES2015
	ScriptTargetES2016 ScriptTarget = core.ScriptTargetES2016
	ScriptTargetES2017 ScriptTarget = core.ScriptTargetES2017
	ScriptTargetES2018 ScriptTarget = core.ScriptTargetES2018
	ScriptTargetES2019 ScriptTarget = core.ScriptTargetES2019
	ScriptTargetES2020 ScriptTarget = core.ScriptTargetES2020
	ScriptTargetES2021 ScriptTarget = core.ScriptTargetES2021
	ScriptTargetES2022 ScriptTarget = core.ScriptTargetES2022
	ScriptTargetES2023 ScriptTarget = core.ScriptTargetES2023
	ScriptTargetES2024 ScriptTarget = core.ScriptTargetES2024
	ScriptTargetES2025 ScriptTarget = core.ScriptTargetES2025
	ScriptTargetESNext ScriptTarget = core.ScriptTargetESNext
)

// ModuleKind API types.
type ModuleKind = core.ModuleKind

const (
	ModuleKindNone     ModuleKind = core.ModuleKindNone
	ModuleKindCommonJS ModuleKind = core.ModuleKindCommonJS
	ModuleKindAMD      ModuleKind = core.ModuleKindAMD
	ModuleKindUMD      ModuleKind = core.ModuleKindUMD
	ModuleKindSystem   ModuleKind = core.ModuleKindSystem
	ModuleKindES2015   ModuleKind = core.ModuleKindES2015
	ModuleKindES2020   ModuleKind = core.ModuleKindES2020
	ModuleKindES2022   ModuleKind = core.ModuleKindES2022
	ModuleKindESNext   ModuleKind = core.ModuleKindESNext
	ModuleKindNode16   ModuleKind = core.ModuleKindNode16
	ModuleKindNode18   ModuleKind = core.ModuleKindNode18
	ModuleKindNode20   ModuleKind = core.ModuleKindNode20
	ModuleKindNodeNext ModuleKind = core.ModuleKindNodeNext
	ModuleKindPreserve ModuleKind = core.ModuleKindPreserve
)

// Tristate constants.
const (
	TSUnknown Tristate = core.TSUnknown
	TSFalse   Tristate = core.TSFalse
	TSTrue    Tristate = core.TSTrue
)

// ParseTestFilesAndSymlinks parses a TypeScript test case file and extracts compiler directives and individual files.
func ParseTestFilesAndSymlinks[T any](
	code string,
	fileName string,
	parseFile func(filename string, content string, fileOptions map[string]string) (T, error),
) (units []T, symlinks map[string]string, currentDir string, globalOptions map[string]string, e error) {
	return testrunner.ParseTestFilesAndSymlinks(code, fileName, parseFile)
}

// NewPathsMap creates a new ordered map for paths.
func NewPathsMap() *collections.OrderedMap[string, []string] {
	return collections.NewOrderedMapWithSizeHint[string, []string](0)
}
`

func main() {
	moduleRoot, err := findModuleRoot()
	if err != nil {
		fmt.Fprintf(os.Stderr, "genbridge: %v\n", err)
		os.Exit(1)
	}

	outDir := filepath.Join(moduleRoot, "third_party", "typescript-go", "tsccbridge")
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "genbridge: failed to create output directory: %v\n", err)
		os.Exit(1)
	}

	outFile := filepath.Join(outDir, "bridge.go")
	formatted, err := format.Source([]byte(bridgeContent))
	if err != nil {
		fmt.Fprintf(os.Stderr, "genbridge: failed to format bridge content: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(outFile, formatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "genbridge: failed to write bridge file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("genbridge: wrote %s\n", outFile)

	patchFile := filepath.Join(moduleRoot, "patches", "inject-resolver.patch")
	tsgoDir := filepath.Join(moduleRoot, "third_party", "typescript-go")
	if err := applyPatch(tsgoDir, patchFile); err != nil {
		fmt.Fprintf(os.Stderr, "genbridge: %v\n", err)
		os.Exit(1)
	}
}

func applyPatch(dir, patchFile string) error {
	// Check if already applied by trying a reverse patch dry-run
	cmdCheck := exec.Command("git", "apply", "--reverse", "--check", patchFile)
	cmdCheck.Dir = dir
	if err := cmdCheck.Run(); err == nil {
		// Reverse patch applies cleanly, meaning the patch is already applied
		return nil
	}

	// Not applied, let's apply it
	cmdApply := exec.Command("git", "apply", patchFile)
	cmdApply.Dir = dir
	out, err := cmdApply.CombinedOutput()
	if err != nil {
		return fmt.Errorf("failed to apply patch %s: %v\n%s", patchFile, err, out)
	}
	fmt.Printf("genbridge: applied patch %s\n", filepath.Base(patchFile))
	return nil
}

// findModuleRoot returns the directory containing the go.mod for
// github.com/szuend/tscc by asking the Go toolchain.
func findModuleRoot() (string, error) {
	out, err := exec.Command("go", "env", "GOMOD").Output()
	if err != nil {
		return "", fmt.Errorf("could not determine module root: %w", err)
	}
	gomod := strings.TrimSpace(string(out))
	if gomod == "" || gomod == os.DevNull {
		return "", fmt.Errorf("not inside a Go module (go env GOMOD returned %q)", gomod)
	}
	return filepath.Dir(gomod), nil
}
